# Generated by Django 5.1.4 on 2025-04-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directions',
            new_name='Direction',
        ),
    ]
