# Generated by Django 5.1.4 on 2025-04-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_auto_20250430_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ('id',), 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
    ]
