# Generated by Django 5.1.4 on 2025-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_alter_direction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='name_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
