# Generated by Django 5.1.4 on 2024-12-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Competency',
                'verbose_name_plural': 'Competencies',
                'db_table': 'competencies',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('knowledge', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionCompetencyCourseLinks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
            ],
            options={
                'db_table': 'profession_competency_course_links',
                'managed': False,
            },
        ),
    ]
