# Generated by Django 5.1.4 on 2025-04-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_professioncompetencycourselinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
