# Generated by Django 5.1.4 on 2025-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20250430_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Competency',
                'verbose_name_plural': 'Competencies',
                'db_table': 'competencies',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Competencies',
        ),
    ]
