# Generated by Django 5.1.4 on 2025-04-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_competency_delete_competencies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
