# Generated by Django 5.1.4 on 2025-04-30 18:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options'),
        ('disciplines', '0003_alter_discipline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ('id',), 'verbose_name': 'Competency', 'verbose_name_plural': 'Competencies'},
        ),
    ]
