# Generated by Django 5.1.4 on 2025-04-30 18:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_competency_options_course_directions_and_more'),
        ('disciplines', '0003_alter_discipline_options_and_more'),
    ]

    operations = [
    ]
