# Generated by Django 5.1.4 on 2024-12-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'db_table': 'disciplines',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplinesDirections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.BigIntegerField()),
            ],
            options={
                'db_table': 'disciplines-directions',
                'managed': False,
            },
        ),
    ]
