# Generated by Django 5.1.4 on 2025-04-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0002_discipline_delete_disciplines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ('id',), 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AlterModelOptions(
            name='disciplinesdirections',
            options={},
        ),
    ]
