# Generated by Django 5.1.4 on 2025-04-30 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_alter_direction_options'),
        ('disciplines', '0003_alter_discipline_options_and_more'),
    ]

    operations = [
    ]
