# Generated by Django 5.1.4 on 2025-05-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0004_disciplinesdirections_direction_and_more'),
    ]

    operations = [
    ]
