# Generated by Django 5.1.4 on 2025-04-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professions',
            new_name='Profession',
        ),
    ]
