# Generated by Django 5.1.4 on 2025-04-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_auto_20250430_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ('id',), 'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
    ]
