# Generated by Django 5.1.4 on 2025-05-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0003_alter_profession_options'),
    ]

    operations = [
    ]
