# Generated by Django 5.1.4 on 2025-04-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfessionCompetencyCourseLinks',
            new_name='ProfessionCompetencyCourseLink',
        ),
    ]
