# Generated by Django 5.1.4 on 2025-04-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20250430_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professioncompetencycourselink',
            options={},
        ),
    ]
