# Generated by Django 5.1.4 on 2025-04-30 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_directions_course_discipline'),
        ('disciplines', '0004_disciplinesdirections_direction_and_more'),
        ('professions', '0003_alter_profession_options'),
        ('recommendations', '0003_alter_professioncompetencycourselink_options'),
    ]

    operations = [
    ]
