# Generated by Django 5.1.4 on 2025-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='Александрович', max_length=150, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
