# Generated by Django 5.1.4 on 2025-04-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
