# Generated by Django 5.1.4 on 2025-04-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_auto_20250430_1346'),
        ('users', '0005_remove_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='directions.direction', verbose_name='Направление'),
        ),
    ]
