# Generated by Django 5.1.4 on 2025-04-30 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_auto_20250430_1331'),
        ('users', '0006_alter_student_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='professions.profession', verbose_name='Профессия'),
        ),
    ]
