# Generated by Django 5.1.4 on 2025-05-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Академическая группа'),
        ),
    ]
