# Generated by Django 5.1.4 on 2024-12-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('knowledge', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('discipline_id', models.BigIntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('direction_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'directions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disciplines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplinesDirections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.BigIntegerField()),
            ],
            options={
                'db_table': 'disciplines-directions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionCompetencyCourseLinks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
            ],
            options={
                'db_table': 'profession_competency_course_links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('knowledge', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professions',
                'managed': False,
            },
        ),
    ]
